package com.fedegiorno.primerparcial.fragments

import android.graphics.Color
import android.os.Bundle
import android.provider.CalendarContract
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.navigation.findNavController
import androidx.preference.PreferenceManager
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.fedegiorno.primerparcial.R
import com.fedegiorno.primerparcial.adapters.CursoListAdapter
import com.fedegiorno.primerparcial.entities.Curso
import com.google.android.material.snackbar.Snackbar

class ListCursosFragment : Fragment() {

    private lateinit var v: View
    private lateinit var recMain2: RecyclerView
    private lateinit var linearLayoutManager: LinearLayoutManager

    private var cursos: MutableList<Curso> = ArrayList()
    private lateinit var cursosListAdapter: CursoListAdapter

    companion object{
        fun newInstance() = ListCursosFragment
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        cursos.add(Curso(name ="La continuidad pedagógica en la emergencia para equipos directivos", descripcion = "La continuidad pedagógica en la emergencia para equipos directivos", profesor = "PEREZ", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="La continuidad pedagógica en la emergencia para docentes", descripcion = "La continuidad pedagógica en la emergencia para docentes", profesor = "CHELLE", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Conocimientos básicos de Moodle - Hacia una pedagogía de la virtualidad", descripcion = "SÍNTESIS: Se trata de un curso nacido en la emergencia orientado a hacer escuela por otros medios. En su recorrido propone una serie de debates en torno a cómo enseñar a la distancia y busca recuperar las propuestas creativas y comprometidas que surgieron en los meses de ASPO. Desde este punto de partida, se invita al docente a abordar las características de la plataforma Moodle como contexto sociotécnico específico para avanzar desde allí sobre algunos interrogantes pedagógicos, con el fin de comenzar a pensar los modos de hacer propios de la virtualidad, en diálogo con la posibilidad de encuentros pedagógicos presenciales en la próxima etapa de DISPO. Durante el trayecto se brinda a los participantes la oportunidad de experimentar la edición de espacios digitales en aulas de práctica Moodle.", profesor = "VIGLIOTA", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="La autoridad directiva en la formación docente", descripcion = "La autoridad directiva en la formación docente", profesor = "GIORNO", puntaje = "0,6", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "120", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Repensar la enseñanza desde una perspectiva institucional: Mesas de Acompañamiento Pedagógico Didáctico y Ateneo (Presencial)", descripcion = "Repensar la enseñanza desde una perspectiva institucional: Mesas de Acompañamiento Pedagógico Didáctico y Ateneo (Presencial)", profesor = "BATTISTA", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Repensar la enseñanza desde una perspectiva institucional: Mesas de Acompañamiento Pedagógico Didáctico y Ateneo (Distancia)", descripcion = "Repensar la enseñanza desde una perspectiva institucional: Mesas de Acompañamiento Pedagógico Didáctico y Ateneo (Distancia)", profesor = "ARIAS", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Enseñar en el nivel secundario. Lazos y prácticas", descripcion = "Enseñar en el nivel secundario. Lazos y prácticas", profesor = "FARIAS GOMEZ", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Por una pedagogía de la conducción escolar en el nivel secundario", descripcion = "Por una pedagogía de la conducción escolar en el nivel secundario", profesor = "NELIDA CASTRO", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Enseñar en el nivel primario. Lazos y prácticas", descripcion = "Enseñar en el nivel primario. Lazos y prácticas", profesor = "ALICIA MUÑIZ", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Por una pedagogía de la conducción escolar en el nivel primario", descripcion = "Por una pedagogía de la conducción escolar en el nivel primario", profesor = "SUSANA GIMENEZ", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Enseñar en el nivel inicial. Lazos y prácticas", descripcion = "Enseñar en el nivel inicial. Lazos y prácticas", profesor = "CRISTINA", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Por una pedagogía de la conducción escolar en el nivel inicial", descripcion = "Por una pedagogía de la conducción escolar en el nivel inicial", profesor = "EVA", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="El Bicentenario de la provincia de Buenos Aires. Identidades, pasados, territorios, sociedades y culturas. Educación Primaria", descripcion = "El Bicentenario de la provincia de Buenos Aires. Identidades, pasados, territorios, sociedades y culturas. Educación Primaria", profesor = "CARLOS GARDEL", puntaje = "0,48", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "40", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="El Bicentenario de la provincia de Buenos Aires. Identidades, pasados, territorios, sociedades y culturas.", descripcion = "¿Cómo pensar el Bicentenario de nuestra provincia? Presentamos un trayecto formativo donde se problematiza la cuestión de la identidad bonaerense, tensionada entre el sentimiento de pertenencia a la Nación y las sólidas filiaciones locales; se analiza la historia provincial a lo largo de los siglos XIX y XX ensayando alternativas a las periodizaciones tradicionales y se aborda la identidad territorial considerando tanto al mundo rural como a los procesos de urbanización. En la última parte del curso se analiza la compleja estructura social de la provincia y algunas características de la cultura bonaerense. Los y las invitamos a pensar juntos el pasado y el presente de Buenos Aires y su lugar en nuestras aulas.", profesor = "EVARISTO URIBURU", puntaje = "0,48", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "40", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        cursos.add(Curso(name ="Escuela, cultura y alfabetizaciones en el mundo contemporáneo", descripcion = "SÍNTESIS: ¿Qué cambia en la escuela cuando ya no tenemos edificio? La siguiente propuesta formativa busca pensar las tensiones entre cultura digital y cultura escolar por fuera de los binarismos ya clásicos. En contraposición (¿o de manera complementaria?), se buscará problematizar la matriz del proyecto escolar en diálogo con las nuevas alfabetizaciones y los modos de hacer, circular y consumir cultura propios de la contemporaneidad y de los nuevos escenarios digitales y conectados. La invitación es a asumir como docentes nuestro lugar de protagonistas de la cultura y sus debates, unos debates que se hacen más urgentes e ineludibles cuando nos vemos frente al desafío de hacer escuela por otros medios.", profesor = "DOMINGO SARMIENTO", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
        ): View {
            // Inflate the layout for this fragment
            v = inflater.inflate(R.layout.fragment_list_cursos, container, false)
            recMain2 = v.findViewById(R.id.reclistcursos)
        return v
    }

    override fun onStart() {
        super.onStart()

        var color: String?
        val Prefs = PreferenceManager.getDefaultSharedPreferences(requireContext())

        color = Prefs.getString("backListColor", "")

        //Toast.makeText(requireContext(),color, Toast.LENGTH_SHORT).show()

        // Configuracion del recyclerview
        recMain2.setHasFixedSize(true)
        linearLayoutManager= LinearLayoutManager(context)
        recMain2.layoutManager = linearLayoutManager

        cursosListAdapter = CursoListAdapter(cursos, requireContext()) { pos ->
            onItemClick(pos)
        }

        recMain2.adapter = cursosListAdapter
        //Se pasa el adaptador al recycler, se muestra en pantalla la lista
    }

    private fun onItemClick(position: Int): Boolean {
//        Toast.makeText(v.context, "Posicion: $position", Toast.LENGTH_LONG).show()
//        Snackbar.make(v,position.toString(), Snackbar.LENGTH_SHORT).show()

//        Toast.makeText(v.context, "Nombre del curso: ${cursos[position].name}", Toast.LENGTH_LONG).show()

        var name: String = cursos[position].name.toString()
        var descripcion: String = cursos[position].descripcion.toString()
        var profesor: String = cursos[position].profesor.toString()
        var puntaje: String = cursos[position].puntaje.toString()
        var inicio: String = cursos[position].inicio.toString()
        var fin: String = cursos[position].fin.toString()
        var horario: String = cursos[position].horario.toString()
        var carga: String = cursos[position].carga.toString()
        var nivel: String = cursos[position].nivel.toString()
        var requisitos: String = cursos[position].requisitos.toString()

        val actionlist = ListCursosFragmentDirections.actionListCursosFragmentToContainerFragment(name, descripcion, profesor, puntaje, inicio, fin, horario, carga, nivel, requisitos)
        v.findNavController().navigate(actionlist)

        return true
    }

}