
package com.fedegiorno.primerparcial.fragments

import android.os.Bundle
import android.util.Log
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import android.widget.Toast
import androidx.navigation.findNavController
import androidx.preference.PreferenceManager
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.fedegiorno.primerparcial.R
import com.fedegiorno.primerparcial.adapters.CursoListAdapter
import com.fedegiorno.primerparcial.databases.appDatabase
import com.fedegiorno.primerparcial.databases.cursoDao
import com.fedegiorno.primerparcial.entities.Curso

class ListCursosFragment : Fragment() {

    private lateinit var v: View
    private lateinit var recCursos: RecyclerView
    private lateinit var linearLayoutManager: LinearLayoutManager

    private var listaCursos: MutableList<Curso> = ArrayList()
    private lateinit var cursosListAdapter: CursoListAdapter

    private var db: appDatabase? = null
    private var cursoDao: cursoDao? = null

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
        ): View {

        // Inflate the layout for this fragment
        v = inflater.inflate(R.layout.fragment_list_cursos, container, false)
        Toast.makeText(v.context, "ListCursosFragment", Toast.LENGTH_SHORT).show()
        recCursos = v.findViewById(R.id.reclistcursos)

        //Instancio el objeto DB
        db = appDatabase.getAppDataBase(v.context)

        //Instancio la interface a la DB
        cursoDao = db?.cursoDao()

        Log.d("CUENTADB", cursoDao?.cuenta().toString())

        if (cursoDao?.cuenta() == 0) { //Valores iniciales de mi Base de Datos
            cursoDao?.insertCurso(Curso(id =1, name ="La continuidad pedagógica en la emergencia para equipos directivos", descripcion = "La continuidad pedagógica en la emergencia para equipos directivos", profesor = "PEREZ", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =2, name ="La continuidad pedagógica en la emergencia para docentes", descripcion = "La continuidad pedagógica en la emergencia para docentes", profesor = "CHELLE", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =3, name ="Conocimientos básicos de Moodle - Hacia una pedagogía de la virtualidad", descripcion = "SÍNTESIS: Se trata de un curso nacido en la emergencia orientado a hacer escuela por otros medios. En su recorrido propone una serie de debates en torno a cómo enseñar a la distancia y busca recuperar las propuestas creativas y comprometidas que surgieron en los meses de ASPO. Desde este punto de partida, se invita al docente a abordar las características de la plataforma Moodle como contexto sociotécnico específico para avanzar desde allí sobre algunos interrogantes pedagógicos, con el fin de comenzar a pensar los modos de hacer propios de la virtualidad, en diálogo con la posibilidad de encuentros pedagógicos presenciales en la próxima etapa de DISPO. Durante el trayecto se brinda a los participantes la oportunidad de experimentar la edición de espacios digitales en aulas de práctica Moodle.", profesor = "VIGLIOTA", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =4, name ="La autoridad directiva en la formación docente", descripcion = "La autoridad directiva en la formación docente", profesor = "GIORNO", puntaje = "0,6", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "120", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =5, name ="Repensar la enseñanza desde una perspectiva institucional: Mesas de Acompañamiento Pedagógico Didáctico y Ateneo (Presencial)", descripcion = "Repensar la enseñanza desde una perspectiva institucional: Mesas de Acompañamiento Pedagógico Didáctico y Ateneo (Presencial)", profesor = "BATTISTA", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =6, name ="Repensar la enseñanza desde una perspectiva institucional: Mesas de Acompañamiento Pedagógico Didáctico y Ateneo (Distancia)", descripcion = "Repensar la enseñanza desde una perspectiva institucional: Mesas de Acompañamiento Pedagógico Didáctico y Ateneo (Distancia)", profesor = "ARIAS", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =7, name ="Enseñar en el nivel secundario. Lazos y prácticas", descripcion = "Enseñar en el nivel secundario. Lazos y prácticas", profesor = "FARIAS GOMEZ", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =8, name ="Por una pedagogía de la conducción escolar en el nivel secundario", descripcion = "Por una pedagogía de la conducción escolar en el nivel secundario", profesor = "NELIDA CASTRO", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =9, name ="Enseñar en el nivel primario. Lazos y prácticas", descripcion = "Enseñar en el nivel primario. Lazos y prácticas", profesor = "ALICIA MUÑIZ", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =10, name ="Por una pedagogía de la conducción escolar en el nivel primario", descripcion = "Por una pedagogía de la conducción escolar en el nivel primario", profesor = "SUSANA GIMENEZ", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =11, name ="Enseñar en el nivel inicial. Lazos y prácticas", descripcion = "Enseñar en el nivel inicial. Lazos y prácticas", profesor = "CRISTINA", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =12, name ="Por una pedagogía de la conducción escolar en el nivel inicial", descripcion = "Por una pedagogía de la conducción escolar en el nivel inicial", profesor = "EVA", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =13, name ="El Bicentenario de la provincia de Buenos Aires. Identidades, pasados, territorios, sociedades y culturas. Educación Primaria", descripcion = "El Bicentenario de la provincia de Buenos Aires. Identidades, pasados, territorios, sociedades y culturas. Educación Primaria", profesor = "CARLOS GARDEL", puntaje = "0,48", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "40", nivel = "Inicial", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =14, name ="El Bicentenario de la provincia de Buenos Aires. Identidades, pasados, territorios, sociedades y culturas.", descripcion = "¿Cómo pensar el Bicentenario de nuestra provincia? Presentamos un trayecto formativo donde se problematiza la cuestión de la identidad bonaerense, tensionada entre el sentimiento de pertenencia a la Nación y las sólidas filiaciones locales; se analiza la historia provincial a lo largo de los siglos XIX y XX ensayando alternativas a las periodizaciones tradicionales y se aborda la identidad territorial considerando tanto al mundo rural como a los procesos de urbanización. En la última parte del curso se analiza la compleja estructura social de la provincia y algunas características de la cultura bonaerense. Los y las invitamos a pensar juntos el pasado y el presente de Buenos Aires y su lugar en nuestras aulas.", profesor = "EVARISTO URIBURU", puntaje = "0,48", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "40", nivel = "Primario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
            cursoDao?.insertCurso(Curso(id =15, name ="Escuela, cultura y alfabetizaciones en el mundo contemporáneo", descripcion = "SÍNTESIS: ¿Qué cambia en la escuela cuando ya no tenemos edificio? La siguiente propuesta formativa busca pensar las tensiones entre cultura digital y cultura escolar por fuera de los binarismos ya clásicos. En contraposición (¿o de manera complementaria?), se buscará problematizar la matriz del proyecto escolar en diálogo con las nuevas alfabetizaciones y los modos de hacer, circular y consumir cultura propios de la contemporaneidad y de los nuevos escenarios digitales y conectados. La invitación es a asumir como docentes nuestro lugar de protagonistas de la cultura y sus debates, unos debates que se hacen más urgentes e ineludibles cuando nos vemos frente al desafío de hacer escuela por otros medios.", profesor = "DOMINGO SARMIENTO", puntaje = "0,44", inicio ="29/3/2021", fin = "1/7/2021", horario = "de 8 a 18 hs", carga = "36", nivel = "Secundario", requisitos = "✔ Desempeñarse en el sistema educativo de la provincia de Buenos Aires, atendiendo a los destinatarios específicos de cada curso. ✔ Disponer de una cuenta en abc. Si no disponen de una pueden crear una aquí: https://autoregistracion.abc.gob.ar/myprofile/guest/new ✔ Conocer su CUIL (11 dígitos) el que será requerido en el formulario de inscripción. Pueden consultarlo aquí: ✔ https://www.anses.gob.ar/consulta/constancia-de-cuil ✔ Todos los cursos otorgan puntaje. ✔ Solo se admitirá la inscripción a un curso por cohorte. Por ello si el docente se inscribe en más de un curso, será tomada por válida la primera de las inscripciones. ✔ Quien tiene una cuenta abc no válida (por ejemplo si su correo abc inicia con su N°deCUIL@abc.gob.ar), necesita escribir a infoayuda@abc.gob.ar enviando un email alternativo, fecha de nacimiento, distrito de residencia, N° de DNI, N° de CUIL, Nombre y apellido completo. Solicitando la validación del correo con el apellido y nombre y así poder inscribirse en los Cursos virtuales de la DFDP. ✔ Las cuentas @abc de los agentes de la DGCyE figuran en el fondo del COULI."))
        }
        return v
    }

    override fun onStart() {
        super.onStart()

        var color: String?
        val Prefs = PreferenceManager.getDefaultSharedPreferences(requireContext())

        listaCursos = cursoDao?.loadAllCursos() as MutableList<Curso>

        color = Prefs.getString("backListColor", "")

        //Toast.makeText(requireContext(),color, Toast.LENGTH_SHORT).show()

        // Configuracion del recyclerview
        recCursos.setHasFixedSize(true)
        linearLayoutManager= LinearLayoutManager(context)
        recCursos.layoutManager = linearLayoutManager

        cursosListAdapter = CursoListAdapter(listaCursos, requireContext()) { pos ->
            onItemClick(pos)
        }

        recCursos.adapter = cursosListAdapter
        //Se pasa el adaptador al recycler, se muestra en pantalla la lista
    }

    private fun onItemClick(position: Int): Boolean {


        // aca debo generar una lista que contenga los cursos cuyo checkbox este seleccionado
        //listaCursosSel = recCursos.forEach { v.ckbCurso.isTrue() }
        // si no hay seleccionado deberia indicarse mediante un snackbar

        var id: Int = listaCursos[position].id
        var name: String = listaCursos[position].name.toString()
        var descripcion: String = listaCursos[position].descripcion
        var profesor: String = listaCursos[position].profesor
        var puntaje: String = listaCursos[position].puntaje
        var inicio: String = listaCursos[position].inicio
        var fin: String = listaCursos[position].fin
        var horario: String = listaCursos[position].horario
        var carga: String = listaCursos[position].carga
        var nivel: String = listaCursos[position].nivel
        var requisitos: String = listaCursos[position].requisitos

        val actionlist = ListCursosFragmentDirections.actionListCursosFragmentToContainerFragment(name, descripcion, profesor, puntaje, inicio, fin, horario, carga, nivel, requisitos, id)
        v.findNavController().navigate(actionlist)

        return true
    }
}
